name: python-base
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.11
  - mamba
  - pip
  - poetry

# Non-standard section listing target platforms for conda-lock:
platforms:
  - linux-64